sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t frankholzweissig/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true frankholzweissig/react-test npm test -- --coverage

after_success:
  - docker build -t frankholzweissig/multi-docker-client ./client
  - docker build -t frankholzweissig/multi-docker-nginx  ./nginx
  - docker build -t frankholzweissig/multi-docker-server ./server
  - docker build -t frankholzweissig/multi-docker-worker ./worker